package org.ibit.wsproxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2021-02-03T16:43:52.564+01:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://wsproxy.ibit.org", name = "pcaPcc")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PcaPcc {

    @WebMethod(action = "http://wsproxy.ibit.org/setEstratificacion")
    @WebResult(name = "setEstratificacionResponse", targetNamespace = "http://wsproxy.ibit.org", partName = "parameters")
    public SetEstratificacionResponseType setEstratificacion(

        @WebParam(partName = "parameters", name = "setEstratificacion", targetNamespace = "http://wsproxy.ibit.org")
        SetEstratificacionRequestType parameters
    );

    @WebMethod(action = "http://wsproxy.ibit.org/getEstratificacion")
    @WebResult(name = "getEstratificacionResponse", targetNamespace = "http://wsproxy.ibit.org", partName = "parameters")
    public GetEstratificacionResponseType getEstratificacion(

        @WebParam(partName = "parameters", name = "getEstratificacion", targetNamespace = "http://wsproxy.ibit.org")
        GetEstratificacionRequestType parameters
    );
}
